version: '3.1'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7-oracle
    restart: always
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database_base
      MYSQL_ROOT_PASSWORD: root
